// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: matchfunction.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api {

  /// <summary>Holder for reflection information generated from matchfunction.proto</summary>
  public static partial class MatchfunctionReflection {

    #region Descriptor
    /// <summary>File descriptor for matchfunction.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MatchfunctionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNtYXRjaGZ1bmN0aW9uLnByb3RvEgNhcGkaDm1lc3NhZ2VzLnByb3RvGhxn",
            "b29nbGUvYXBpL2Fubm90YXRpb25zLnByb3RvIogBCgpSdW5SZXF1ZXN0EhIK",
            "CnByb2ZpbGVfaWQYASABKAkSEwoLcHJvcG9zYWxfaWQYAiABKAkSEQoJcmVz",
            "dWx0X2lkGAMgASgJEisKDG1hdGNoX29iamVjdBgEIAEoCzIVLm1lc3NhZ2Vz",
            "Lk1hdGNoT2JqZWN0EhEKCXRpbWVzdGFtcBgFIAEoCSINCgtSdW5SZXNwb25z",
            "ZTJSCg1NYXRjaEZ1bmN0aW9uEkEKA1J1bhIPLmFwaS5SdW5SZXF1ZXN0GhAu",
            "YXBpLlJ1blJlc3BvbnNlIheC0+STAhEaDC92MS9mdW5jdGlvbjoBKkINWgtp",
            "bnRlcm5hbC9wYmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Messages.MessagesReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.RunRequest), global::Api.RunRequest.Parser, new[]{ "ProfileId", "ProposalId", "ResultId", "MatchObject", "Timestamp" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.RunResponse), global::Api.RunResponse.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Request message sent to the MMF.
  /// </summary>
  public sealed partial class RunRequest : pb::IMessage<RunRequest> {
    private static readonly pb::MessageParser<RunRequest> _parser = new pb::MessageParser<RunRequest>(() => new RunRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RunRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.MatchfunctionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RunRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RunRequest(RunRequest other) : this() {
      profileId_ = other.profileId_;
      proposalId_ = other.proposalId_;
      resultId_ = other.resultId_;
      matchObject_ = other.matchObject_ != null ? other.matchObject_.Clone() : null;
      timestamp_ = other.timestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RunRequest Clone() {
      return new RunRequest(this);
    }

    /// <summary>Field number for the "profile_id" field.</summary>
    public const int ProfileIdFieldNumber = 1;
    private string profileId_ = "";
    /// <summary>
    /// Developer-chosen profile name, state storage key for the match object.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProfileId {
      get { return profileId_; }
      set {
        profileId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "proposal_id" field.</summary>
    public const int ProposalIdFieldNumber = 2;
    private string proposalId_ = "";
    /// <summary>
    /// The ID against which, the generated proposal should be stored.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProposalId {
      get { return proposalId_; }
      set {
        proposalId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "result_id" field.</summary>
    public const int ResultIdFieldNumber = 3;
    private string resultId_ = "";
    /// <summary>
    /// Final result ID. MMF needs to know this in case of errors where proposal generation can be shortcircuited.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ResultId {
      get { return resultId_; }
      set {
        resultId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "match_object" field.</summary>
    public const int MatchObjectFieldNumber = 4;
    private global::Messages.MatchObject matchObject_;
    /// <summary>
    /// The match object containing the details of the match to be generated.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Messages.MatchObject MatchObject {
      get { return matchObject_; }
      set {
        matchObject_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 5;
    private string timestamp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RunRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RunRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProfileId != other.ProfileId) return false;
      if (ProposalId != other.ProposalId) return false;
      if (ResultId != other.ResultId) return false;
      if (!object.Equals(MatchObject, other.MatchObject)) return false;
      if (Timestamp != other.Timestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ProfileId.Length != 0) hash ^= ProfileId.GetHashCode();
      if (ProposalId.Length != 0) hash ^= ProposalId.GetHashCode();
      if (ResultId.Length != 0) hash ^= ResultId.GetHashCode();
      if (matchObject_ != null) hash ^= MatchObject.GetHashCode();
      if (Timestamp.Length != 0) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ProfileId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ProfileId);
      }
      if (ProposalId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ProposalId);
      }
      if (ResultId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ResultId);
      }
      if (matchObject_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(MatchObject);
      }
      if (Timestamp.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ProfileId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProfileId);
      }
      if (ProposalId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProposalId);
      }
      if (ResultId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResultId);
      }
      if (matchObject_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MatchObject);
      }
      if (Timestamp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RunRequest other) {
      if (other == null) {
        return;
      }
      if (other.ProfileId.Length != 0) {
        ProfileId = other.ProfileId;
      }
      if (other.ProposalId.Length != 0) {
        ProposalId = other.ProposalId;
      }
      if (other.ResultId.Length != 0) {
        ResultId = other.ResultId;
      }
      if (other.matchObject_ != null) {
        if (matchObject_ == null) {
          matchObject_ = new global::Messages.MatchObject();
        }
        MatchObject.MergeFrom(other.MatchObject);
      }
      if (other.Timestamp.Length != 0) {
        Timestamp = other.Timestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ProfileId = input.ReadString();
            break;
          }
          case 18: {
            ProposalId = input.ReadString();
            break;
          }
          case 26: {
            ResultId = input.ReadString();
            break;
          }
          case 34: {
            if (matchObject_ == null) {
              matchObject_ = new global::Messages.MatchObject();
            }
            input.ReadMessage(matchObject_);
            break;
          }
          case 42: {
            Timestamp = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RunResponse : pb::IMessage<RunResponse> {
    private static readonly pb::MessageParser<RunResponse> _parser = new pb::MessageParser<RunResponse>(() => new RunResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RunResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.MatchfunctionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RunResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RunResponse(RunResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RunResponse Clone() {
      return new RunResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RunResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RunResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RunResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
