// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mmlogic.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api {

  /// <summary>Holder for reflection information generated from mmlogic.proto</summary>
  public static partial class MmlogicReflection {

    #region Descriptor
    /// <summary>File descriptor for mmlogic.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MmlogicReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1tbWxvZ2ljLnByb3RvEgNhcGkaDm1lc3NhZ2VzLnByb3RvGhxnb29nbGUv",
            "YXBpL2Fubm90YXRpb25zLnByb3RvIjkKEUdldFByb2ZpbGVSZXF1ZXN0EiQK",
            "BW1hdGNoGAEgASgLMhUubWVzc2FnZXMuTWF0Y2hPYmplY3QiOgoSR2V0UHJv",
            "ZmlsZVJlc3BvbnNlEiQKBW1hdGNoGAEgASgLMhUubWVzc2FnZXMuTWF0Y2hP",
            "YmplY3QiPQoVQ3JlYXRlUHJvcG9zYWxSZXF1ZXN0EiQKBW1hdGNoGAEgASgL",
            "MhUubWVzc2FnZXMuTWF0Y2hPYmplY3QiGAoWQ3JlYXRlUHJvcG9zYWxSZXNw",
            "b25zZSJBChRHZXRQbGF5ZXJQb29sUmVxdWVzdBIpCgtwbGF5ZXJfcG9vbBgB",
            "IAEoCzIULm1lc3NhZ2VzLlBsYXllclBvb2wiQgoVR2V0UGxheWVyUG9vbFJl",
            "c3BvbnNlEikKC3BsYXllcl9wb29sGAEgASgLMhQubWVzc2FnZXMuUGxheWVy",
            "UG9vbCJHChtHZXRBbGxJZ25vcmVkUGxheWVyc1JlcXVlc3QSKAoNaWdub3Jl",
            "X3BsYXllchgBIAEoCzIRLm1lc3NhZ2VzLklsSW5wdXQiQAocR2V0QWxsSWdu",
            "b3JlZFBsYXllcnNSZXNwb25zZRIgCgZyb3N0ZXIYASABKAsyEC5tZXNzYWdl",
            "cy5Sb3N0ZXIiRQoZTGlzdElnbm9yZWRQbGF5ZXJzUmVxdWVzdBIoCg1pZ25v",
            "cmVfcGxheWVyGAEgASgLMhEubWVzc2FnZXMuSWxJbnB1dCI+ChpMaXN0SWdu",
            "b3JlZFBsYXllcnNSZXNwb25zZRIgCgZyb3N0ZXIYASABKAsyEC5tZXNzYWdl",
            "cy5Sb3N0ZXIymwQKB01tTG9naWMSagoKR2V0UHJvZmlsZRIWLmFwaS5HZXRQ",
            "cm9maWxlUmVxdWVzdBoXLmFwaS5HZXRQcm9maWxlUmVzcG9uc2UiK4LT5JMC",
            "JRIjL3YxL2xvZ2ljL21hdGNoLXByb2ZpbGVzL3ttYXRjaC5pZH0SbwoOQ3Jl",
            "YXRlUHJvcG9zYWwSGi5hcGkuQ3JlYXRlUHJvcG9zYWxSZXF1ZXN0GhsuYXBp",
            "LkNyZWF0ZVByb3Bvc2FsUmVzcG9uc2UiJILT5JMCHhoZL3YxL2xvZ2ljL21h",
            "dGNoLXByb3Bvc2FsczoBKhJ7Cg1HZXRQbGF5ZXJQb29sEhkuYXBpLkdldFBs",
            "YXllclBvb2xSZXF1ZXN0GhouYXBpLkdldFBsYXllclBvb2xSZXNwb25zZSIx",
            "gtPkkwIrEikvdjEvbG9naWMvcGxheWVyLXBvb2xzL3twbGF5ZXJfcG9vbC5u",
            "YW1lfTABEl0KFEdldEFsbElnbm9yZWRQbGF5ZXJzEiAuYXBpLkdldEFsbEln",
            "bm9yZWRQbGF5ZXJzUmVxdWVzdBohLmFwaS5HZXRBbGxJZ25vcmVkUGxheWVy",
            "c1Jlc3BvbnNlIgASVwoSTGlzdElnbm9yZWRQbGF5ZXJzEh4uYXBpLkxpc3RJ",
            "Z25vcmVkUGxheWVyc1JlcXVlc3QaHy5hcGkuTGlzdElnbm9yZWRQbGF5ZXJz",
            "UmVzcG9uc2UiAEINWgtpbnRlcm5hbC9wYmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Messages.MessagesReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.GetProfileRequest), global::Api.GetProfileRequest.Parser, new[]{ "Match" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.GetProfileResponse), global::Api.GetProfileResponse.Parser, new[]{ "Match" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.CreateProposalRequest), global::Api.CreateProposalRequest.Parser, new[]{ "Match" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.CreateProposalResponse), global::Api.CreateProposalResponse.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.GetPlayerPoolRequest), global::Api.GetPlayerPoolRequest.Parser, new[]{ "PlayerPool" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.GetPlayerPoolResponse), global::Api.GetPlayerPoolResponse.Parser, new[]{ "PlayerPool" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.GetAllIgnoredPlayersRequest), global::Api.GetAllIgnoredPlayersRequest.Parser, new[]{ "IgnorePlayer" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.GetAllIgnoredPlayersResponse), global::Api.GetAllIgnoredPlayersResponse.Parser, new[]{ "Roster" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.ListIgnoredPlayersRequest), global::Api.ListIgnoredPlayersRequest.Parser, new[]{ "IgnorePlayer" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.ListIgnoredPlayersResponse), global::Api.ListIgnoredPlayersResponse.Parser, new[]{ "Roster" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetProfileRequest : pb::IMessage<GetProfileRequest> {
    private static readonly pb::MessageParser<GetProfileRequest> _parser = new pb::MessageParser<GetProfileRequest>(() => new GetProfileRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetProfileRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.MmlogicReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProfileRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProfileRequest(GetProfileRequest other) : this() {
      match_ = other.match_ != null ? other.match_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProfileRequest Clone() {
      return new GetProfileRequest(this);
    }

    /// <summary>Field number for the "match" field.</summary>
    public const int MatchFieldNumber = 1;
    private global::Messages.MatchObject match_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Messages.MatchObject Match {
      get { return match_; }
      set {
        match_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetProfileRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetProfileRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Match, other.Match)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (match_ != null) hash ^= Match.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (match_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Match);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (match_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Match);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetProfileRequest other) {
      if (other == null) {
        return;
      }
      if (other.match_ != null) {
        if (match_ == null) {
          match_ = new global::Messages.MatchObject();
        }
        Match.MergeFrom(other.Match);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (match_ == null) {
              match_ = new global::Messages.MatchObject();
            }
            input.ReadMessage(match_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetProfileResponse : pb::IMessage<GetProfileResponse> {
    private static readonly pb::MessageParser<GetProfileResponse> _parser = new pb::MessageParser<GetProfileResponse>(() => new GetProfileResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetProfileResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.MmlogicReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProfileResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProfileResponse(GetProfileResponse other) : this() {
      match_ = other.match_ != null ? other.match_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProfileResponse Clone() {
      return new GetProfileResponse(this);
    }

    /// <summary>Field number for the "match" field.</summary>
    public const int MatchFieldNumber = 1;
    private global::Messages.MatchObject match_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Messages.MatchObject Match {
      get { return match_; }
      set {
        match_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetProfileResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetProfileResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Match, other.Match)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (match_ != null) hash ^= Match.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (match_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Match);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (match_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Match);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetProfileResponse other) {
      if (other == null) {
        return;
      }
      if (other.match_ != null) {
        if (match_ == null) {
          match_ = new global::Messages.MatchObject();
        }
        Match.MergeFrom(other.Match);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (match_ == null) {
              match_ = new global::Messages.MatchObject();
            }
            input.ReadMessage(match_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class CreateProposalRequest : pb::IMessage<CreateProposalRequest> {
    private static readonly pb::MessageParser<CreateProposalRequest> _parser = new pb::MessageParser<CreateProposalRequest>(() => new CreateProposalRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateProposalRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.MmlogicReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateProposalRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateProposalRequest(CreateProposalRequest other) : this() {
      match_ = other.match_ != null ? other.match_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateProposalRequest Clone() {
      return new CreateProposalRequest(this);
    }

    /// <summary>Field number for the "match" field.</summary>
    public const int MatchFieldNumber = 1;
    private global::Messages.MatchObject match_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Messages.MatchObject Match {
      get { return match_; }
      set {
        match_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateProposalRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateProposalRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Match, other.Match)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (match_ != null) hash ^= Match.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (match_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Match);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (match_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Match);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateProposalRequest other) {
      if (other == null) {
        return;
      }
      if (other.match_ != null) {
        if (match_ == null) {
          match_ = new global::Messages.MatchObject();
        }
        Match.MergeFrom(other.Match);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (match_ == null) {
              match_ = new global::Messages.MatchObject();
            }
            input.ReadMessage(match_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class CreateProposalResponse : pb::IMessage<CreateProposalResponse> {
    private static readonly pb::MessageParser<CreateProposalResponse> _parser = new pb::MessageParser<CreateProposalResponse>(() => new CreateProposalResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateProposalResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.MmlogicReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateProposalResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateProposalResponse(CreateProposalResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateProposalResponse Clone() {
      return new CreateProposalResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateProposalResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateProposalResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateProposalResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class GetPlayerPoolRequest : pb::IMessage<GetPlayerPoolRequest> {
    private static readonly pb::MessageParser<GetPlayerPoolRequest> _parser = new pb::MessageParser<GetPlayerPoolRequest>(() => new GetPlayerPoolRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetPlayerPoolRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.MmlogicReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPlayerPoolRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPlayerPoolRequest(GetPlayerPoolRequest other) : this() {
      playerPool_ = other.playerPool_ != null ? other.playerPool_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPlayerPoolRequest Clone() {
      return new GetPlayerPoolRequest(this);
    }

    /// <summary>Field number for the "player_pool" field.</summary>
    public const int PlayerPoolFieldNumber = 1;
    private global::Messages.PlayerPool playerPool_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Messages.PlayerPool PlayerPool {
      get { return playerPool_; }
      set {
        playerPool_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetPlayerPoolRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetPlayerPoolRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PlayerPool, other.PlayerPool)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (playerPool_ != null) hash ^= PlayerPool.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (playerPool_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PlayerPool);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (playerPool_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerPool);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetPlayerPoolRequest other) {
      if (other == null) {
        return;
      }
      if (other.playerPool_ != null) {
        if (playerPool_ == null) {
          playerPool_ = new global::Messages.PlayerPool();
        }
        PlayerPool.MergeFrom(other.PlayerPool);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (playerPool_ == null) {
              playerPool_ = new global::Messages.PlayerPool();
            }
            input.ReadMessage(playerPool_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetPlayerPoolResponse : pb::IMessage<GetPlayerPoolResponse> {
    private static readonly pb::MessageParser<GetPlayerPoolResponse> _parser = new pb::MessageParser<GetPlayerPoolResponse>(() => new GetPlayerPoolResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetPlayerPoolResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.MmlogicReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPlayerPoolResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPlayerPoolResponse(GetPlayerPoolResponse other) : this() {
      playerPool_ = other.playerPool_ != null ? other.playerPool_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPlayerPoolResponse Clone() {
      return new GetPlayerPoolResponse(this);
    }

    /// <summary>Field number for the "player_pool" field.</summary>
    public const int PlayerPoolFieldNumber = 1;
    private global::Messages.PlayerPool playerPool_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Messages.PlayerPool PlayerPool {
      get { return playerPool_; }
      set {
        playerPool_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetPlayerPoolResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetPlayerPoolResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PlayerPool, other.PlayerPool)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (playerPool_ != null) hash ^= PlayerPool.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (playerPool_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PlayerPool);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (playerPool_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerPool);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetPlayerPoolResponse other) {
      if (other == null) {
        return;
      }
      if (other.playerPool_ != null) {
        if (playerPool_ == null) {
          playerPool_ = new global::Messages.PlayerPool();
        }
        PlayerPool.MergeFrom(other.PlayerPool);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (playerPool_ == null) {
              playerPool_ = new global::Messages.PlayerPool();
            }
            input.ReadMessage(playerPool_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllIgnoredPlayersRequest : pb::IMessage<GetAllIgnoredPlayersRequest> {
    private static readonly pb::MessageParser<GetAllIgnoredPlayersRequest> _parser = new pb::MessageParser<GetAllIgnoredPlayersRequest>(() => new GetAllIgnoredPlayersRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllIgnoredPlayersRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.MmlogicReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllIgnoredPlayersRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllIgnoredPlayersRequest(GetAllIgnoredPlayersRequest other) : this() {
      ignorePlayer_ = other.ignorePlayer_ != null ? other.ignorePlayer_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllIgnoredPlayersRequest Clone() {
      return new GetAllIgnoredPlayersRequest(this);
    }

    /// <summary>Field number for the "ignore_player" field.</summary>
    public const int IgnorePlayerFieldNumber = 1;
    private global::Messages.IlInput ignorePlayer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Messages.IlInput IgnorePlayer {
      get { return ignorePlayer_; }
      set {
        ignorePlayer_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllIgnoredPlayersRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllIgnoredPlayersRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(IgnorePlayer, other.IgnorePlayer)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ignorePlayer_ != null) hash ^= IgnorePlayer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ignorePlayer_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(IgnorePlayer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ignorePlayer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IgnorePlayer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllIgnoredPlayersRequest other) {
      if (other == null) {
        return;
      }
      if (other.ignorePlayer_ != null) {
        if (ignorePlayer_ == null) {
          ignorePlayer_ = new global::Messages.IlInput();
        }
        IgnorePlayer.MergeFrom(other.IgnorePlayer);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (ignorePlayer_ == null) {
              ignorePlayer_ = new global::Messages.IlInput();
            }
            input.ReadMessage(ignorePlayer_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetAllIgnoredPlayersResponse : pb::IMessage<GetAllIgnoredPlayersResponse> {
    private static readonly pb::MessageParser<GetAllIgnoredPlayersResponse> _parser = new pb::MessageParser<GetAllIgnoredPlayersResponse>(() => new GetAllIgnoredPlayersResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAllIgnoredPlayersResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.MmlogicReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllIgnoredPlayersResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllIgnoredPlayersResponse(GetAllIgnoredPlayersResponse other) : this() {
      roster_ = other.roster_ != null ? other.roster_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAllIgnoredPlayersResponse Clone() {
      return new GetAllIgnoredPlayersResponse(this);
    }

    /// <summary>Field number for the "roster" field.</summary>
    public const int RosterFieldNumber = 1;
    private global::Messages.Roster roster_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Messages.Roster Roster {
      get { return roster_; }
      set {
        roster_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAllIgnoredPlayersResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAllIgnoredPlayersResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Roster, other.Roster)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (roster_ != null) hash ^= Roster.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (roster_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Roster);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (roster_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Roster);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAllIgnoredPlayersResponse other) {
      if (other == null) {
        return;
      }
      if (other.roster_ != null) {
        if (roster_ == null) {
          roster_ = new global::Messages.Roster();
        }
        Roster.MergeFrom(other.Roster);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (roster_ == null) {
              roster_ = new global::Messages.Roster();
            }
            input.ReadMessage(roster_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ListIgnoredPlayersRequest : pb::IMessage<ListIgnoredPlayersRequest> {
    private static readonly pb::MessageParser<ListIgnoredPlayersRequest> _parser = new pb::MessageParser<ListIgnoredPlayersRequest>(() => new ListIgnoredPlayersRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ListIgnoredPlayersRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.MmlogicReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListIgnoredPlayersRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListIgnoredPlayersRequest(ListIgnoredPlayersRequest other) : this() {
      ignorePlayer_ = other.ignorePlayer_ != null ? other.ignorePlayer_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListIgnoredPlayersRequest Clone() {
      return new ListIgnoredPlayersRequest(this);
    }

    /// <summary>Field number for the "ignore_player" field.</summary>
    public const int IgnorePlayerFieldNumber = 1;
    private global::Messages.IlInput ignorePlayer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Messages.IlInput IgnorePlayer {
      get { return ignorePlayer_; }
      set {
        ignorePlayer_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ListIgnoredPlayersRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ListIgnoredPlayersRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(IgnorePlayer, other.IgnorePlayer)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ignorePlayer_ != null) hash ^= IgnorePlayer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ignorePlayer_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(IgnorePlayer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ignorePlayer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IgnorePlayer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ListIgnoredPlayersRequest other) {
      if (other == null) {
        return;
      }
      if (other.ignorePlayer_ != null) {
        if (ignorePlayer_ == null) {
          ignorePlayer_ = new global::Messages.IlInput();
        }
        IgnorePlayer.MergeFrom(other.IgnorePlayer);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (ignorePlayer_ == null) {
              ignorePlayer_ = new global::Messages.IlInput();
            }
            input.ReadMessage(ignorePlayer_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ListIgnoredPlayersResponse : pb::IMessage<ListIgnoredPlayersResponse> {
    private static readonly pb::MessageParser<ListIgnoredPlayersResponse> _parser = new pb::MessageParser<ListIgnoredPlayersResponse>(() => new ListIgnoredPlayersResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ListIgnoredPlayersResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.MmlogicReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListIgnoredPlayersResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListIgnoredPlayersResponse(ListIgnoredPlayersResponse other) : this() {
      roster_ = other.roster_ != null ? other.roster_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListIgnoredPlayersResponse Clone() {
      return new ListIgnoredPlayersResponse(this);
    }

    /// <summary>Field number for the "roster" field.</summary>
    public const int RosterFieldNumber = 1;
    private global::Messages.Roster roster_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Messages.Roster Roster {
      get { return roster_; }
      set {
        roster_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ListIgnoredPlayersResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ListIgnoredPlayersResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Roster, other.Roster)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (roster_ != null) hash ^= Roster.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (roster_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Roster);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (roster_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Roster);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ListIgnoredPlayersResponse other) {
      if (other == null) {
        return;
      }
      if (other.roster_ != null) {
        if (roster_ == null) {
          roster_ = new global::Messages.Roster();
        }
        Roster.MergeFrom(other.Roster);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (roster_ == null) {
              roster_ = new global::Messages.Roster();
            }
            input.ReadMessage(roster_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
